### ISSUE TITLE
no check for increasing order in domain for variables

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#12]
According the "Remark 5" in XCSP3 specifications (page 26)

> The integer values and intervals listed in the domain of an integer variable must
> always be in increasing order, without several occurrences of the same value. For example,
> 0..10 10 is forbidden to be the content of an element <var>.

Unfortunately there isn't check for increasing order in the current parser so are accepted variables defined as follows

    <var id="x"> -10..10 10 </var>
    <var id="y"> 10..-10 </var>
    <var id="z"> 5 0..10 </var>

It seems to me that the simplest point where to add this type of check is in the `class XDomainInteger` (XCSP3Domain.h).

Adding a new member `top` (protected or private)

    int top { std::numeric_limits<int>::min() };

and rewriting methods `addValue()` and `addInterval()` to use and update this value (by example: as follows)

        void addValue (int v) {
            if ( v <= top )
               throw std::runtime_error{"not sequence domain"};

            addEntity(new XIntegerValue( top = v ));
        }

        void addInterval (int min, int max) {
            if ( (max <= min) || (min <= top) )
               throw std::runtime_error{"not sequence domain"};

            addEntity(new XIntegerInterval(min, top = max));
        }

should be possible exclude this tipe of wrong variables without big changes in the code.

Unfortunately, in `XDomainInteger` isn't available the string corresponding to the domain so the message of the exception isn't really useful.

**Comment by massimomorara** [comment]
The following is a possible patch
[patch.txt](https://github.com/xcsp3team/XCSP3-CPP-Parser/files/1170913/patch.txt)

**Comment by xcsp3team** [comment]
Done. Thanks.

**Comment by xcsp3team** [comment]
In the near future, we shall give a new tool that permits to test if an instance is well-formed or not. This tool is being finalized.

**Comment by massimomorara** [comment]
Good to know.
With "tools" do you mean a separate executable that validate a xml in xcsp3 format or do you intend adding now callbacks in your parser?
Anyway... waiting for it.
