### ISSUE TITLE
Bad `catch` and `throw`

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#21]
Shortly: the following `catch`-and-`throw` code ("src/XCSP3CoreParser.cc", `parse(istream &in)` method)

    } catch(runtime_error &e) {
        // ???
        if ( parserCtxt && parserCtxt->input )
           cout << "Exception at line " << parserCtxt->input->line << endl;
        else
           cout << "Exception at undefined line";
        throw (e);
    }

has two flaws:

(1) intercept only exceptions of type `std::runtime_error` and derived

    } catch(runtime_error &e) {

so a different exception (`std::bad_alloc`, by example) isn't intercepted (and, I suppose, can be useful intercept it)

(2) the exception is re-`throw` by **copy**

        throw (e);

so if the catch intercept an exception of a type **derived** from `std::runtime_error`, is re-`throw` as `std::runtime_error`, losing it's specificity.

Solutions:

For (1) I suggest to catch all `std::exception const &` exceptions

    } catch ( std::exception const & ) {

or, maybe better, **all** exceptions

    } catch ( ... ) {

For (2) I suggest to re-`throw` the currently handled exception, so

    throw;

instead of a copy (`throw(e);`).

Long description: I'm writing a simple program that load XCSP3 instances, using your callback-parser, and try to solve them using Gecode.

When, parsing the instances, I encounter a non-supported feature, I throw an exception of a type, `unsupportedExc`, that I've derived from `std::runtime_error`.

The problem is that your `catch` and `throw` code intercept my exception as `std::runtime_error` and rethrow it as `std::runtime_error`, not as `unsupportedExc`. So my `main()` intercept a copy, of wrong type, of the original exception. So I end with `s UNKNOWN` instead of `s UNSUPPORTED`.

To avoid this sort of problem it's important re-`throw` the original exception

    throw; // instead of throw(e)

Taking in count that the exception is intercepted and (copied and) rethrow but not used, I also suggest to extend the range of exception intercepted to all standard exceptions

    } catch ( std::exception const & ) {

or (maybe better) to all exceptions

    } catch ( ... ) {

**Comment by massimomorara** [comment]
Another couple of points.

(3) the messages

    if ( parserCtxt && parserCtxt->input )
       cout << "Exception at line " << parserCtxt->input->line << endl;
    else
       cout << "Exception at undefined line";

The first one ends with a `std::endl`; the second one without it; maybe is better to add a `std::endl` also for the second

       cout << "Exception at undefined line" << endl;

(4) If I understand correctly, both messages are incompatible with the output format prescribed for competitions; maybe you could start them with "c ", to make the compatible with a comment line, so

    if ( parserCtxt && parserCtxt->input )
       std::cout << "c Exception at line " << parserCtxt->input->line << std::endl;
    else
       std::cout << "c Exception at undefined line" << std::end;

Otherwise you could send them to standard error to avoid to "contaminate" the competition standard output.

    if ( parserCtxt && parserCtxt->input )
       std::cerr << "Exception at line " << parserCtxt->input->line << std::endl;
    else
       std::cerr << "Exception at undefined line" << std::end;

**Comment by audemard** [comment]
Thank you to help us to improve the code.
It is fixed.
