### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#23]
Playing with valgrind, I see that the member `manager` in class `XMLParser` is allocated in constructor

    this->manager = new XCSP3Manager(cb, variablesList);

but (as far I can understand) never deallocated.

Also to make it clearer, I suggest to rewrite the destructor of the class as follows

    XMLParser::~XMLParser() {
        for ( auto & tag : tagList )
           delete tag.second;
        delete unknownTagHandler;
        delete manager;
    }

**Comment by xcsp3team** [comment]
fixed.
