### ISSUE TITLE
Warnings for unused arguments in callbacks methods

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#25]
Again: I **strongly** suggest the systematic use of "-Wall -Wextra -ansi -pedantic".

To avoid the resulting warnings, in 2017 I've proposed some changes and, in particular, the deletion of the identifiers of the unused arguments in funcions/methods declaration.

Unfortunately, the names of the unused arguments is important in "include/XCSP3CoreCallbacks.h" to understand the callbacks.

So I propose another strategy: instructions of type

    (void)unusedArgument;

in the body of methods.

Esample: instead of

        virtual void beginInstance(InstanceType type) { }

I propose

        virtual void beginInstance(InstanceType type) { (void)type; }

I add a zip file with a modified "include/XCSPCoreCallbacks.h" with all `(void)variable;` required.

[callbacks-h.zip](https://github.com/xcsp3team/XCSP3-CPP-Parser/files/4496728/callbacks-h.zip)

**Comment by xcsp3team** [comment]
Many thanks.
Fixed.
