### ISSUE TITLE
Corrections for some minor warning

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#26]
Compiling with "-Wall -Wextra -ansi -pedantic" I get some warnings that is simple to avoid.

(1) In "src/XCSP3Tree.cc", in the `Tree::createBasicParameter()` method, a `std::invalid_argument` exception is catched by value

        } catch (invalid_argument e) {

The compiler (g++) print the following warning

    XCSP3Tree.cc:135:31: warning: catching polymorphic type ‘class std::invalid_argument’ by value [-Wcatch-value=]

Avoid this is simple: the exception should be catched by constant reference

        } catch (invalid_argument const & e) {

or, considering the the catched `e` exception isn't used, also

        } catch (invalid_argument const &) {

(2) in "src/XMLParser.cc", method `XMLParser::characters()`, there is unused variable inside a `while`

     char c = *brk;

You can delete or comment this line

(3) in "src/XMLParserTags.cc" there are three unused parameters for three method:

- `attributes`, in `XMLParser::AnnotationsTagAction::beginTag()`,
- `attributes`, in `XMLParser::DecisionTagAction::beginTag()`
- `last`, in `XMLParser::DecisionTagAction::text()` 

To avoid this warnings, you can delete the names of the arguments or you can `(void)` them inside the body of the methods.

**Comment by xcsp3team** [comment]
Thanks.
Fixed.
