### ISSUE TITLE
Request for Complete API Documentation

### ISSUE THREAD

**Issue by domainexpert** [xcsp3team/XCSP3-CPP-Parser#4]
It seems the best API documentation atm is the HOWTO, which is incomplete.

**Comment by domainexpert** [comment]
What we want to do is to translate XCSP3 constraints into a C program. One of the first problem that we need to tackle is the parsing of an intensional constraint into its syntax tree. I am wondering if anyone has an example on this.

**Comment by rafa-hub** [comment]
I will also appreciate parsing examples.

**Comment by xcsp3team** [comment]
I am going to provide in the parser a Tree implementation that will help you for managing intensional constraints.
On which aspects do you think the howto needs to be completed (in priority)?

**Comment by xcsp3team** [comment]
Thank you for your interest in XCSP3.
We are sorry for the delay here, but we had a problem with the email address attached to notifications.

**Comment by xcsp3team** [comment]
I add a Tree class in order to evaluate and manage instensional constraint.
Please take a look at it.

**Comment by rafa-hub** [comment]
Tree class looks promising, but I'am having trouble with the last update.
I work on graphs resolution, so I convert CSP problems into graphs. More examples in file processing could be great.

**Comment by xcsp3team** [comment]
Can you explain in detail your troubles ?

**Comment by rafa-hub** [comment]
It failed compiling because climits and find_if. I haven't check its functionality yet.

**Comment by xcsp3team** [comment]
We fixed some compilations errors. Please pull the project and it should compile.

**Comment by rafa-hub** [comment]
You are right, it is fixed. It works now fine. I will check the tree class.
I would need to access <args> values, how could I get them? Which callback method is invoked?

**Comment by xcsp3team** [comment]
Sorry if I misunderstood your question.
In order to evaluate an expression, you need to create a Tree
Tree t("eq(z,add(x,3))");

Then, in order to give values to z and x you need a map : 
std::map<string, int> tuple;
tuple["z"] = 4;
tuple["x"] = 1;

in this case x=1 and z = 4.
Then, to evaluate : t.evaluate(tuple)

it returns 0 (if false) or 1 (if true).
Take a look to the file samples/testTree.cc

So, to access values to variables, you need a map....

**Comment by rafa-hub** [comment]
Thank you for your help and your patience. The Parser is a good piece of software and the XCSP format document is well written, but sometimes it could be good to have a more specific link between them.

**Comment by xcsp3team** [comment]
This is a good idea. I am going to add links from the parser to related constraints (documentation pdf and also online documentation).

**Comment by xcsp3team** [comment]
I provide online documentation in XCSP3CoreCallbacks.h file.
All callback functions are documented with a link to the official doc and an example.

**Comment by rafa-hub** [comment]
Great!

**Comment by domainexpert** [comment]
@xcsp3team I appreciate all the new additions a lot. Thanks to @rafa-hub as well for guiding the discussion. Previously I was not even sure if there is a parser for the intensional constraints or not. Also, the comments in XCSP3CoreCallbacks.h look very useful. We are currently not using the new tree parser, but we are still working on our XCSP3 to C translators. For now, I think it is time to close this issue with big thanks.
