### ISSUE TITLE
a couple of compilation errors

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#7]
Hi.

Playing again with your parser, I've obtained a couple of errors.

The first one is in include/XCSP3TreeNode.h, in NodeIn::evaluate(); from the following line

    return find(set.begin(), set.end(), nb) != set.end();

I get

> ../include/XCSP3TreeNode.h:537:51: error: no matching function for call to ‘find(std::vector<int>::iterator, std::vector<int>::iterator, int&)’

The problem is simple to solve: it's enough to include the correct header for `std::find` that is 

    #include <algorithm>

The second one is in src/XCSPTree.cc, in the `min()` (with three arguments) function.

The problem is that isn't included the correct header for `INT_MAX` (that is `<cstdint>`) but you're using C++11 and I suggest to rewrite the function using C++11 features (templates, numeric limits class, template variadic min function), that is (including `<limits>` and `<algorithm>`)

    template <typename T>
    static int min(T v1, T v2, T v3) {
        if (v1 == -1) v1 = std::numeric_limits<T>::max();
        if (v2 == -1) v2 = std::numeric_limits<T>::max();
        if (v3 == -1) v3 = std::numeric_limits<T>::max();

        return std::min( { v1, v2, v3 } );
    }

p.s.: a patch file, to also avoid a lot of warnings, follows

**Comment by massimomorara** [comment]
The patch file
 
[patch.txt](https://github.com/xcsp3team/XCSP3-CPP-Parser/files/1150438/patch.txt)

**Comment by xcsp3team** [comment]
Thanks again for your contributions.
Gilles.
