### ISSUE TITLE
presumed wrong case for default value for @type attribute in <var .../> and <array .../> elements  

### ISSUE THREAD

**Issue by massimomorara** [xcsp3team/XCSP3-CPP-Parser#8]
Trying to parse an XML with the following `var` element

    <var id="x2" type="integer"> 0..6 </var>

I get the following error

    Exception at line 5

	    Unexpected exception :
	    XCSP3Core expected type=Integer for tag <var>

and is accepted the same element with the "Integer" (initial upper-case) value for @type

    <var id="x2" type="Integer"> 0..6 </var>

As far I know (XCSP3 specifications), the correct value for type is "integer" (all lower-case).

There is the same problem with `<array ...>`.

I propose the following patch

[patch.txt](https://github.com/xcsp3team/XCSP3-CPP-Parser/files/1160212/patch.txt)

**Comment by xcsp3team** [comment]
You are right.
The good token is "integer" (completely lower-cased).
Actually, all similar tokens (symbolic, real, set, ...) are totally lower-cased.
I think that Gilles (currently, on holidays ;-)) will accept your patch.

 Christophe

**Comment by xcsp3team** [comment]
Yes, it is done.
Thanks.
